services:
  stun:
    image: instrumentisto/coturn:latest
    command: >
      turnserver --stun-only
      --listening-port=3478
      --listening-ip=0.0.0.0
      --no-tls --no-dtls --fingerprint
    ports:
      - target: 3478
        protocol: udp
      - target: 3478
        protocol: tcp
    profiles: ['stun', 'emu', 'e2e']

  rtdb-emulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.firebase
    working_dir: /app
    volumes:
      - ./scripts:/app/scripts:ro
      - ./config/firebase:/app/config:ro
      - firebase-emulator-cache:/opt/firebase
      - firebase-emulator-cache-ui:/opt/firebase/.cache
    environment:
      PROJECT_ID: demo-peach-share
      FIREBASE_EMULATOR_DOWNLOAD_PATH: /opt/firebase
      XDG_CACHE_HOME: /opt/firebase/.cache
    entrypoint: ['/app/scripts/emulator-entrypoint.sh']
    profiles: ['rtdb', 'emu', 'e2e']

  playwright:
    build:
      context: ..
      dockerfile: docker/Dockerfile.e2e
    working_dir: /src
    volumes:
      - ..:/src:delegated
      - pnpm-store:/var/pnpm-store
      - node_modules:/src/node_modules
    environment:
      CI: '1'
      MODE: emu
      BASE_URL: http://web:5173
      HEADED: '1'
      PLAYWRIGHT_BROWSERS_PATH: /ms-playwright
      DISPLAY: ':99' # чтобы явно
      VNC_PORT: '5900'
      VNC_GEOMETRY: '1920x1080x24'
    shm_size: '1gb'
    depends_on: [web]
    ports:
      - '5901:5900' # VNC наружу (только на localhost)
    entrypoint: ['/src/docker/scripts/e2e-entrypoint.sh']
    profiles: ['e2e']

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    working_dir: /src
    volumes:
      - ..:/src:delegated
      - pnpm-store:/var/pnpm-store
      - node_modules:/src/node_modules
    environment:
      MODE: emu
      CHOKIDAR_USEPOLLING: '1'
      WATCHPACK_POLLING: 'true'
    entrypoint: ['/src/docker/scripts/web-entrypoint.sh']
    depends_on:
      - rtdb-emulator
      - stun
    profiles: ['dev', 'e2e']

volumes:
  node_modules:
  pnpm-store:
  firebase-emulator-cache:
  firebase-emulator-cache-ui:
