FROM node:24-alpine3.22
RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.22/community/" >> /etc/apk/repositories \
 && apk update && apk add --no-cache openjdk21-jre-headless bash
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk
ENV PATH="$JAVA_HOME/bin:$PATH"
RUN npm i -g firebase-tools
