FROM traefik:v3.6.9 AS traefik_bin
RUN test -x /usr/local/bin/traefik

FROM alpine:3.20

RUN apk add --no-cache \
  bash curl openssl ca-certificates nss-tools

COPY --from=traefik_bin /usr/local/bin/traefik /usr/local/bin/traefik

# mkcert (1.4.4)
RUN curl -fsSL -o /usr/local/bin/mkcert \
    https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64 \
 && chmod +x /usr/local/bin/mkcert