services:
  rtdb-emulator:
    environment:
      NODE_OPTIONS: "--trace-uncaught"
    ports:
      - "4000:4000"
      - "9000:9000"
      - "9099:9099"
      - "5001:5001"
    profiles: ['integration-test']
