FROM mcr.microsoft.com/playwright:v1.56.1-noble
WORKDIR /src

# pnpm
RUN corepack enable && corepack prepare pnpm@10.18.2 --activate
RUN pnpm config set store-dir /var/pnpm-store

# Xvfb + VNC + лёгкий WM
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    xvfb x11vnc fluxbox xauth x11-xserver-utils \
 && rm -rf /var/lib/apt/lists/*