name: CI
on:
  push:
    branches: ['**']
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:24.3.0-alpine

    steps:
      - name: Install git for checkout
        run: apk add --no-cache git openssh-client

      - uses: actions/checkout@v5

      - name: Setup pnpm 10.18.2
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build
